inveniosoftware/invenio-formatter

.travis.yml
invenio_formatter/__init__.py
invenio_formatter/engine.py
invenio_formatter/models.py
invenio_formatter/registry.py
invenio_formatter/template_context_functions/tfn_get_back_to_search_links.py
invenio_formatter/upgrades/formatter_2014_08_01_recjson.py
invenio_formatter/upgrades/formatter_2014_08_25_add_bibfmt_kind.py
invenio_formatter/upgrades/formatter_2014_10_29_add_mime_type.py
invenio_formatter/utils.py
setup.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

global: code style improvements

---

.travis.yml
CHANGES.rst
MANIFEST.in
RELEASE-NOTES.rst
invenio_formatter/translations/de/LC_MESSAGES/messages.po
invenio_formatter/translations/es/LC_MESSAGES/messages.po
invenio_formatter/translations/fr/LC_MESSAGES/messages.po
invenio_formatter/translations/it/LC_MESSAGES/messages.po
invenio_formatter/version.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

Invenio-Formatter v0.1.0

---

invenio_formatter/upgrades/formatter_2014_08_25_add_bibfmt_kind.py
invenio_formatter/upgrades/formatter_2014_10_29_add_mime_type.py
invenio_formatter/upgrades/formatter_2015_01_29_removal_of_format_tables.py

* FIX: import of invenio_upgrader
Signed-off-by: Eamonn Maguire eamonnmag@gmail.com

global: fix import of invenio_upgrader

---

AUTHORS.rst
CHANGES.rst
MANIFEST.in
RELEASE-NOTES.rst
invenio_formatter/translations/de/LC_MESSAGES/messages.po
invenio_formatter/translations/es/LC_MESSAGES/messages.po
invenio_formatter/translations/fr/LC_MESSAGES/messages.po
invenio_formatter/translations/invenio.pot
invenio_formatter/translations/it/LC_MESSAGES/messages.po
invenio_formatter/version.py
setup.cfg

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

Invenio-Formatter v0.2.1

---

setup.py

* FIX Adds missing dependency to pyyaml>=3.11.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

installation: pyyaml>=3.11

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_formatter/version.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

release: v1.0.0a1

---

invenio_formatter/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

version: post-release bump

---

.travis.yml
invenio_formatter/context_processors/__init__.py
invenio_formatter/context_processors/badges.py
invenio_formatter/templates/invenio_formatter/macros/meta.html
invenio_formatter/views.py
setup.py
tests/test_template_context_processors.py
tests/test_template_macros.py
tests/test_views.py

* Adds a macro that generates a badge using a title, a value and
optionally, a background color.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

macros: addition of `badge` macro

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_formatter/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v1.0.0a2

---

MANIFEST.in
docs/api.rst
examples/app.py
examples/templates/index.html
invenio_formatter/context_processors/badges.py
invenio_formatter/ext.py
invenio_formatter/filters/datetime.py
invenio_formatter/views.py
setup.cfg

* Improves documentation. (addresses #27)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

docs: addition of param and result sections

---

.travis.yml
.tx/config
AUTHORS.rst
MANIFEST.in
docs/api.rst
docs/conf.py
docs/index.rst
examples/app.py
invenio_formatter/context_processors/badges.py
invenio_formatter/templates/invenio_formatter/macros/meta.html
invenio_formatter/version.py
invenio_formatter/views.py
run-tests.sh
setup.cfg
tests/test_invenio_formatter.py
tests/test_template_context_processors.py
tests/test_template_macros.py
tests/test_views.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

global: code style, copyrights, authors

---

docs/api.rst
docs/conf.py
docs/configuration.rst
setup.py

* Adds configuration.rst.
* Updates intersphinx mapping.
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

[feature-beta] docs: cookiecutter structure syncing

---

.editorconfig
.gitignore
.travis.yml
.tx/config
AUTHORS.rst
CHANGES.rst
CONTRIBUTING.rst
INSTALL.rst
MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/api.rst
docs/conf.py
docs/examplesapp.rst
examples/app.py
examples/templates/index.html
invenio_formatter/__init__.py
invenio_formatter/ext.py
run-tests.sh
setup.py
tests/test_examples_app.py

Related: https://github.com/inveniosoftware/invenio-formatter/issues/37
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

global: initial cookiecutter syncing and docs

---

CHANGES.rst
README.rst
RELEASE-NOTES.rst
invenio_formatter/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

release: v1.0.0b1

---

docs/requirements.txt
invenio_formatter/__init__.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

docs: readthedocs build fix

---

INSTALL.rst

Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

docs: addition of cairo apt-get snipplet in installation

---

examples/templates/index.html
invenio_formatter/__init__.py
invenio_formatter/ext.py
invenio_formatter/filters/datetime.py
invenio_formatter/templates/invenio_formatter/macros/meta.html

* Fixes issue which occured when rendering publication dates older than
1900-01-01. (closes #47)
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

views: meta_highwire rendering fix for old dates

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_formatter/version.py

Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

release: v1.0.0b2

---

docs/examplesapp.rst
examples/app.py

* fix example app rendering problems on readthedocs. (closes #52)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

docs: fix example app rendering problems on readthedocs

---

invenio_formatter/config.py
invenio_formatter/views.py
tests/test_views.py

views: no cache for badge view

---

setup.py

global: pin pytest and bump sphinx version

---

CHANGES.rst
examples/app.py
examples/templates/index.html
invenio_formatter/ext.py
invenio_formatter/filters/html.py
invenio_formatter/version.py
setup.py
tests/conftest.py
tests/test_examples_app.py
tests/test_filters.py

* Centralises the HTML sanitisation for Invenio.
Addresses https://github.com/inveniosoftware/invenio-previewer/issues/96.

filters: add HTML sanitization filter

---

invenio_formatter/templates/semantic-ui/invenio_formatter/macros/badges.html
invenio_formatter/templates/semantic-ui/invenio_formatter/macros/meta.html

templates: add semantic ui template 

---

invenio_formatter/templates/semantic-ui/invenio_formatter/macros/badges.html

badges: style snippets

---

CHANGES.rst
INSTALL.rst
invenio_formatter/version.py

Release v1.1.0

---

babel.ini
invenio_formatter/translations/messages.pot
setup.cfg

* remove jinja extensions
* adds fuzzy string true
* update .pot
related inveniosoftware/invenio-app-rdm#1664

i18n: update translation files

---

docs/conf.py
invenio_formatter/translations/de/LC_MESSAGES/messages.po

* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664

i18n: adds german translations

---

CHANGES.rst
invenio_formatter/__init__.py
run-tests.sh
setup.cfg

- fix: --dry-run ignored
- setup: remove flask-babelex

fix flask babelex

---

invenio_formatter/ext.py
invenio_formatter/filters/datetime.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2281
Preview:

filters: add humanized time template filter

---

CHANGES.rst
invenio_formatter/__init__.py

Please describe briefly your pull request.
**Reminder**
2. You agree that you have the right to license …

release: v1.3.0

---

invenio_formatter/templates/invenio_formatter/macros/badges.html
invenio_formatter/templates/semantic-ui/invenio_formatter/macros/badges.html

Closes https://github.com/inveniosoftware/invenio-github/issues/115
Fixes semantic HTML for badges

badges: semantic html fixes

---

invenio_formatter/templates/invenio_formatter/macros/badges.html
invenio_formatter/templates/semantic-ui/invenio_formatter/macros/badges.html

Please describe briefly your pull request.
Fix https://github.com/zenodo/zenodo/issues/2204
After:
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

Replace reStructedText with reStructuredText

---

invenio_formatter/views.py

Closes Issue https://github.com/zenodo/ops/issues/405
**Reminder**
2. You agree that you have the right …

badge: added sanitization for value

---

examples/app.py
invenio_formatter/__init__.py
invenio_formatter/config.py
invenio_formatter/context_processors/__init__.py
invenio_formatter/context_processors/badges.py
invenio_formatter/ext.py
invenio_formatter/filters/__init__.py
invenio_formatter/filters/datetime.py
invenio_formatter/views.py
tests/conftest.py
tests/test_filters.py
tests/test_invenio_formatter.py
tests/test_template_context_processors.py
tests/test_template_macros.py
tests/test_views.py

The imports of print_function and absolute_import from __future__ were
never used, and in other recent Invenio module updates, the import
statement was removed. This commit removes the import and brings
things in line with those other modules.
The imports of `print_function` and `absolute_import` from `__future__` were
never used, and in other recent Invenio module updates, the import
statement was removed. This commit removes the import and brings
things in line with those other modules.
(None)
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …

Remove unused imports from __future__

---

invenio_formatter/context_processors/badges.py
invenio_formatter/views.py

Closes Issue https://github.com/zenodo/ops/issues/405
**Reminder**
2. You agree that you have the right …

badge: applied html escaping to value and title

---

CHANGES.rst
invenio_formatter/__init__.py

Please describe briefly your pull request.
**Reminder**
2. You agree that you have the right to license …

release: v2.0.3

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
invenio_formatter/__init__.py
setup.cfg

- setup: pin dependencies
- setup: change to reusable workflows
- release: v2.0.4

pin dependencies

---

CHANGES.rst
invenio_formatter/__init__.py
setup.cfg

- setup: bump major dependencies
- release: v3.0.0

bump major

---

INSTALL.rst

Resolves documentation issue by deleting non-existant option described in https://github.com/inveniosoftware/invenio-formatter/issues/92
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

docs: update install instructions

---

invenio_formatter/views.py
tests/test_views.py

badges: add color URL parameter
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current …

badges: add color URL parameter
